In [2]:
import numpy as np

a: np.ndarray = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


# Scaler Values

In [8]:
a: np.ndarray = np.array(100)
display(a)
display(a.shape)
display(a.dtype)
display(a.ndim)
display(type(a))
display(a.size)
display(a.itemsize)

1

4

# Vector Values

In [9]:
a: np.ndarray = np.array([1, 2, 3, 4])
display(a)
display(a.shape)
display(a.dtype)
display(a.ndim)
display(type(a))
display(a.size)
display(a.itemsize)

array([1, 2, 3, 4])

(4,)

dtype('int32')

1

numpy.ndarray

4

4

# Matrix Values

In [11]:
data : np.ndarray = np.array([[1,3,4,5,],
    [2,3,4,5,],
    [3,3,4,5,],
    [4,3,4,5,]])

display(data)
display(data.shape)
display(data.dtype)
display(data.ndim)
display(type(data))
display(data.size)
display(data.itemsize)

array([[1, 3, 4, 5],
       [2, 3, 4, 5],
       [3, 3, 4, 5],
       [4, 3, 4, 5]])

(4, 4)

dtype('int32')

2

numpy.ndarray

16

4

## Numpy with NDArray typing support

In [35]:
from nptyping import NDArray, Shape, UInt64

data: NDArray[Shape["10"], UInt64] = np.arange(1, 10).astype(UInt64)
print(data)
data2 = data + 5
print(data2)

[1 2 3 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12 13 14]


In [38]:
# Numpy advanced operations vs List Operations
ndata: NDArray[Shape["10"], UInt64] = np.arange(1, 21).astype(UInt64)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 500
print(ndata)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[  1   2   3   4   5 500 500 500 500 500 500  12  13  14  15  16  17  18
  19  20]
[ 1  5  8 10]


# Bool Arrays in Numpy

In [39]:
from nptyping import Bool
ndata2: NDArray[Shape["4"], UInt64] = np.array([1, 5, 8, 10])

print(ndata2)

select: NDArray[Shape["4"],Bool] = np.array([True, False, True, False])
print(ndata2[select])

[ 1  5  8 10]
[1 8]


In [40]:
ndata: NDArray[Shape["4"],UInt64] = np.array([1, 2, 4, 7, 10])
ndata[ndata % 2 == 0]

array([ 2,  4, 10])

In [47]:
state_bank: NDArray[Shape["4"],UInt64] = np.array([1, 3, 6, 7, 10])
ubl_bank: NDArray[Shape["20"],UInt64] = np.random.randint(1,200,20).astype(UInt64)
print(state_bank)
print(ubl_bank)
print(state_bank[np.in1d(state_bank,ubl_bank)])
print(np.intersect1d(state_bank,ubl_bank))

[ 1  3  6  7 10]
[127 158  69  95 144  93  32  40  46   3  80 105  82  84 176  79  93 116
 167 133]
[3]
[3.]


In [49]:
x: NDArray[Shape["20"],UInt64] = np.array([1, 2, 3, 9, 5])
y: NDArray[Shape["20"],UInt64] = np.array([6, 4, 3, 8, 5])
np.where(x>=y,x,y)

array([6, 4, 3, 9, 5])

In [53]:
a: NDArray[Shape["*, *"], UInt64] = np.array([[1, 2, 3, 4],
                                            [5, 6, 7, 8],
                                            [9, 10, 11, 12],])
print(a)
a: NDArray[Shape["*, *"], UInt64] = np.array([[1, 2, 3],
                                            [5, 6, 7],
                                            [9, 10, 11],])
print(a)
a: NDArray[Shape["*, *"], UInt64] = np.array([[1, 2],
                                            [5, 6],
                                            [9, 10],])
print(a)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [60]:
a : NDArray[Shape["Size, Size"], UInt64] = np.array([[1, 2, 3, 4, 5, 6],
                                                    [7, 8, 9, 10, 11, 12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [69]:
# a: NDArray[Shape["Size, Size"], UInt64] = np.arange(4*4).reshape(4,4).astype(UInt64)

# print(a)

# a: NDArray[Shape["Size, Size"], UInt64] = np.arange(3*2).reshape(3,2).astype(UInt64)

# print(a)

a: NDArray[Shape["Size, Size"], UInt64] = np.arange(4*3*2).reshape(4,3,2).astype(UInt64)

# print(a)

print(a[::2,::,::])
print(a[[0,-1],::,::])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[12 13]
  [14 15]
  [16 17]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[18 19]
  [20 21]
  [22 23]]]


In [74]:
a: NDArray[Shape["5"],UInt64] = np.asarray([[1, 2, 3, 4, 5, 6, 7],
                                            [8, 9, 10, 11, 12, 13, 14],])
print(a[a % 2 == 0])

ndata: NDArray[Shape["20"],UInt64] = np.arange(1,21).astype(UInt64)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())
print(ndata.argmin())
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())

[ 2  4  6  8 10 12 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
0
10.5
Mode 10.50
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


In [95]:
from typing import Any
# Create a NumPy array with the elements [1, 2, 3, 4, 5].
nexer: NDArray[Shape["5"], UInt64] = np.array([1, 2, 3, 4, 5])

print(nexer)

# Create a 3x3 NumPy array with all elements being 0.
nexer2: NDArray[Shape["3, 3 "], UInt64] = np.zeros((3,3)).astype(UInt64)
print(nexer2)

# excercise 3
nexer3: NDArray[Shape["10"],UInt64] = np.arange(10,21,2).astype(UInt64)
print(nexer3)

# excercise 4 Create a NumPy array containing the squares of numbers from 1 to 10.
nexer4: NDArray[Shape["10"], UInt64] = np.square(np.arange(1,11))
print(nexer4)

# excercise 5 
arr1: NDArray[Shape["5"], UInt64] = np.array([1, 2, 3, 4, 5])
arr2: NDArray[Shape["5"], UInt64] = np.array([6,7,8,9,19])
print(np.concatenate((arr1,arr2)))

# exercise 6
arr1: NDArray[Shape["5"], UInt64] = np.array([1, 2, 3, 4, 5,6,7,8,9,19])
print(f"The Sum of Arr1 is {arr1.sum()}")

# exercise 7 
print(f"The min of Arr1 is {arr1.min()}")
print(f"The max of Arr1 is {arr1.max()}")

[1 2 3 4 5]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
[ 1  2  3  4  5  6  7  8  9 19]
The Sum of Arr1 is 64
The min of Arr1 is 1
The max of Arr1 is 19
